### ISSUE TITLE
goeasy.js:4 WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by Bruce-Qi** [GoEasySupport/goeasy#2]
Hi ,I encounter the issue,goeasy.js:4 WebSocket is already in CLOSING or CLOSED state.but I open them in two different broswer,and set the accual channel for them.so I do not know how to resolve the issue,thx

**Comment by xiukongtiao** [comment]
Dear Bruce,

What is the challenge for you,  can not subscribe  a channel, or can not receive a message?
We have sent you our contact in the account activate email, you can add GoEasy as your  friend on Skype or QQ and get help conveniently.


Thank you!

**Comment by GoEasySupport** [comment]
Dear Bruce, 

What is the challenge for you, can not subscribe a channel, or can not receive a message? 
We have sent you our Skype and QQ in the account activate email, you can add GoEasy as your friend on Skype and QQ and get the help conveniently.

Cheers, 
Team GoEasy

**Comment by Bruce-Qi** [comment]
Hi Team GoEasy,
  thx you for your reply,now it works ok.and this is caused by using to many channels in different device,and we make them in one channel,and seperate message by sepcial userid ,and now works ok,
